BookBorrowPy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_borrow/', include('book_borrow.urls')),
    path('book_borrow/login/', include('login.urls')),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
    path('', views.do_login, name='login'),
    path('logout/', views.do_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.models import User


class ChangePasswordForm(forms.Form):
    username = forms.CharField(required=True, error_messages={'required': '用户名不能为空'})
    password = forms.CharField(required=True, error_messages={'required': '密码不能为空'})
    sure_password = forms.CharField(required=True, error_messages={'required': '确认密码不能为空'})

    def clean_username(self):
        username = self.cleaned_data['username']

        save_user_count = User.objects.filter(username=username).count()
        if save_user_count != 1:
            raise forms.ValidationError('用户名异常，请联系管理员核查')

        return username

    def clean_sure_password(self):
        password = self.cleaned_data['password']
        sure_password = self.cleaned_data['sure_password']

        if password == 'sxfs123456':
            raise forms.ValidationError('密码不可与默认密码一致')

        if not password or not sure_password or password != sure_password:
            raise forms.ValidationError('密码填写不匹配')

        return password

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.hashers import check_password

from .forms import ChangePasswordForm


@require_http_methods(["GET", "POST"])
def do_login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = authenticate(request, username=username, password=password)
    if user is not None:
        if check_password('sxfs123456', user.password):
            return render(request, 'edit_password.html', {
                'username': username
            })
        login(request, user)
        return redirect(reverse('book_borrow:index'))
    else:
        return render(request, 'login.html', {
            'username': username,
            'login_error': "用户名或密码错误"
        })


@login_required(login_url='login:login')
@require_POST
def do_logout(request):
    logout(request)
    return redirect(reverse('book_borrow:index'))


@require_POST
def change_password(request):
    form = ChangePasswordForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = User.objects.get(username=username)
        user.set_password(password)
        user.save()
        return redirect(reverse('login:login'))
    else:
        return render(request, 'edit_password.html', {
            'username': request.POST.get('username', ''),
            'form': form
        })

login/templates/edit_password.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico' %}">

    <title>方是图书借阅系统</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
</head>

<body>
<form class="form-signin" action="{% url 'login:change_password' %}" method="post">
    {% csrf_token %}
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">修改默认密码</h1>
    </div>
    <input hidden="hidden" name="username" value="{{ username }}">
    <div class="form-label-group">
        <input type="password" id="password" class="form-control" placeholder="请输入新密码" name="password" required>
        <label for="password">密码</label>
    </div>
    <div class="form-label-group">
        <input type="password" id="sure_password" class="form-control" placeholder="请重复输入新密码" name="sure_password" required>
        <label for="sure_password">确认密码</label>
    </div>

    {% if form.errors %}
        <div class="form-label-group">
            <div class="alert alert-danger" role="alert">
                {{ form.errors.username }}
            </div>
            <div class="alert alert-danger" role="alert">
                {{ form.errors.sure_password }}
            </div>
        </div>
    {% endif %}
    <div class="form-label-group">
        <div class="alert alert-danger" role="alert" id="password_error" style="display: none">

        </div>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="button" onclick="change_password()">修改</button>
    <p class="mt-5 mb-3 text-muted text-center">© 山西方是科技有限公司</p>
</form>
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">
    function change_password() {
    		var isError = false;

    		var password = $("#password").val();
      		if (password == null || password == "") {
      		    $("#password_error").html('');
      		    $("#password_error").text('新密码不能为空');
      			$("#password_error").css("display","block")
      			isError = true;
      		} else {
      			$("#password_error").css("display","none")

      			var sure_password = $("#sure_password").val();
      			if ($("#password").val() != $("#sure_password").val()) {
      				$("#password_error").html('');
                    $("#password_error").text('请确认密码是否正确');
                    $("#password_error").css("display","block")
      				isError = true;
      			} else {
      				$("#password_error").css("display","none")
      			}
      		}

      		if (!isError) {
      			$("form").submit();
      		}
		}
</script>
</body>
</html>

login/templates/login.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'icon/favicon.ico' %}">

    <title>方是图书借阅系统</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
</head>

<body>
<form class="form-signin" action="{% url 'login:login' %}" method="post">
    {% csrf_token %}
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">欢迎使用方是图书借阅系统</h1>
    </div>
    <div class="form-label-group">
        <input type="text" id="username" class="form-control" placeholder="请输入用户名" name="username" required>
        <label for="username">用户名</label>
    </div>

    <div class="form-label-group">
        <input type="password" id="password" class="form-control" placeholder="请输入密码" name="password" required>
        <label for="password">密码</label>
    </div>
    <div class="form-label-group">
        {% if login_error %}
            <div class="alert alert-danger" role="alert">
                {{ login_error }}
            </div>
        {% endif %}
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    <p class="mt-5 mb-3 text-muted text-center">© 山西方是科技有限公司</p>
</form>
</body>
</html>