BookBorrowPy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_borrow/', include('book_borrow.urls')),
    path('book_borrow/login/', include('login.urls')),
]

book_borrow/urls.py
from django.urls import path
from . import views


app_name = 'book_borrow'
urlpatterns = [
    path('', views.index, name='index'),
    path('book_lists/', views.book_lists, name='book_lists'),
    path('input_book_info/', views.input_book_info, name='input_book_info'),
    path('update_child_class/<str:main_class_id>/', views.update_child_class, name='update_child_class'),
    path('commit_book_info', views.commit_book_info, name='commit_book_info'),
    path('book_detailed_info/<int:book_id>', views.book_detailed_info, name='book_detailed_info'),
    path('book_borrowing/', views.book_borrowing, name='book_borrowing'),
    path('renew_book/', views.renew_book, name='renew_book'),
    path('delete_book/', views.delete_book, name='delete_book'),
    path('return_book/', views.return_book, name='return_book'),
    path('book_borrow_items/', views.book_borrow_items, name='book_borrow_items'),
    path('borrow_history/', views.borrow_history, name='borrow_history'),
    path('book_class_tree/', views.book_class_tree, name='book_class_tree'),
    path('jump_class_tree/', views.jump_class_tree, name='jump_class_tree'),
    path('input_book_class/', views.input_book_class, name='input_book_class'),
    path('find_book_class_parent/', views.find_book_class_parent, name='find_book_class_parent'),
    path('del_book_class/', views.del_book_class, name='del_book_class'),
    path('update_book_class/', views.update_book_class, name='update_book_class'),
    path('expert_borrow_history/', views.expert_borrow_history, name='expert_borrow_history'),
    path('expert_stock_book/', views.expert_stock_book, name='expert_stock_book'),
    path('update_book_info/<int:book_id>', views.update_book_info, name='update_book_info'),
    path('user_manage/', views.user_manage, name='user_manage'),
    path('add_user/', views.add_user, name='add_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
    path('', views.do_login, name='login'),
    path('logout/', views.do_logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
]

book_borrow/models.py
from django.db import models


class Book(models.Model):
    book_name = models.CharField(verbose_name='图书名称', max_length=255, blank=False, null=False, unique=True)
    author = models.CharField(verbose_name='作者', max_length=100, blank=False, null=False)
    brief_introduction = models.CharField(verbose_name='简介', max_length=4096, default='', null=False)
    price = models.DecimalField(verbose_name='价格', max_digits=8, decimal_places=2)
    book_num = models.IntegerField(verbose_name='图书数量', default=1, null=False)
    referee = models.CharField(verbose_name='推荐人', max_length=100, default='', null=False)
    recommended_reasons = models.CharField(verbose_name='推荐理由', max_length=4096, default='', null=False)
    press = models.CharField(verbose_name='出版社', max_length=1024, default='', null=False)
    borrow_num = models.IntegerField(verbose_name='借阅数量', default=0, null=False)
    cover_img_pathname = models.CharField(verbose_name='封面图片路径名',
                                          max_length=255, default='', null=False)


class BookClass(models.Model):
    parent_id = models.IntegerField(verbose_name='父Id', blank=False, null=False)
    name = models.CharField(verbose_name='类型名称', max_length=255, blank=False, null=False)
    book_list = models.ManyToManyField(Book)


class BookBorrowItem(models.Model):
    book_name = models.CharField(verbose_name='图书名称', max_length=255, blank=False, null=False)
    borrower = models.CharField(verbose_name='借阅人', max_length=100, blank=False, null=False)
    borrower_department = models.CharField(verbose_name='借阅人所属部门', max_length=100, blank=False, null=False)
    borrowed_time = models.DateTimeField(verbose_name='借阅时间', blank=False, null=False)
    end_time = models.DateTimeField(verbose_name='截止时间', blank=False, null=False)


class BookBorrowHistory(models.Model):
    book_name = models.CharField(verbose_name='图书名称', max_length=255, blank=False, null=False)
    borrower = models.CharField(verbose_name='借阅人', max_length=100, blank=False, null=False)
    borrower_department = models.CharField(verbose_name='借阅人所属部门', max_length=100, blank=False, null=False)
    borrowed_time = models.DateTimeField(verbose_name='借阅时间', blank=False, null=False)
    book_return_time = models.DateTimeField(verbose_name='还书时间', blank=False, null=False)

book_borrow/forms.py
from django import forms


class InputBookForms(forms.Form):
    book_name = forms.CharField(required=True, error_messages={'required': '必须输入书名'})
    author = forms.CharField(required=True, error_messages={'required': '必须输入作者'})
    price = forms.DecimalField(required=True, decimal_places=2,
                               error_messages={'required': '必须输入定价',
                                               'decimal_places': '价格格式不正确'})
    book_num = forms.IntegerField(required=True, min_value=1,
                                  error_messages={'required': '必须输入图书数量',
                                                  'min_value': '请输入正确的图书数量'})

book_borrow/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings

from profiles.models import UserProfile

from BookBorrowPy import error_code
from .forms import InputBookForms
from .models import BookClass, Book, BookBorrowItem, BookBorrowHistory
import json
import time
import os
import datetime
import pymysql
import pandas as pd


# 图书管理系统首页
@require_GET
def index(request):
    search_name = request.GET.get('search_name')
    main_class_id = request.GET.get('main_class_id')
    child_class_id = request.GET.get('child_class_id')
    if search_name is None:
        search_name = ''
    if main_class_id is None:
        main_class_id = '-1'
    if child_class_id is None:
        child_class_id = '-1'

    if search_name == '':
        if child_class_id == '-1':
            if main_class_id == '-1':
                book_list = Book.objects.values('id', 'book_name', 'brief_introduction', 'cover_img_pathname')
            else:
                search_book_class = BookClass.objects.get(id=main_class_id)
                book_list = search_book_class.book_list.all()
        else:
            search_book_class = BookClass.objects.get(id=child_class_id)
            book_list = search_book_class.book_list.all()
    else:
        book_list_search = Book.objects.values('id', 'book_name', 'brief_introduction', 'cover_img_pathname'). \
            filter(book_name__contains=search_name)
        if child_class_id == '-1':
            if main_class_id == '-1':
                book_list = book_list_search
            else:
                search_book_class = BookClass.objects.get(id=main_class_id)
                book_list = search_book_class.book_list.all() | book_list_search
        else:
            search_book_class = BookClass.objects.get(id=child_class_id)
            book_list = search_book_class.book_list.all() | book_list_search

    paginator = Paginator(book_list, 4)

    page = request.GET.get('page')

    book_main_class_list = BookClass.objects.filter(parent_id=0)
    if len(book_main_class_list) == 0:
        book_main_class_list = []
        book_child_class_list = []
    else:
        if main_class_id != '':
            book_child_class_list = BookClass.objects.filter(parent_id=main_class_id)
        else:
            book_child_class_list = BookClass.objects.filter(parent_id=book_main_class_list[0].id)
            if len(book_child_class_list) == 0:
                book_child_class_list = []
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {
        'books': books,
        'book_main_class_list': book_main_class_list,
        'book_child_class_list': book_child_class_list,
        'search_name': search_name,
        'main_class_id': int(main_class_id),
        'child_class_id': int(child_class_id)
    })


# 图书列表
@require_GET
def book_lists(request):
    book_list = Book.objects.values('id', 'book_name', 'author',  'book_num', 'borrow_num')

    paginator = Paginator(book_list, 10)

    page = request.GET.get('page')

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)
    return render(request, 'book_list.html', {
        'books': books
    })


# 跳转登记图书信息
@login_required(login_url='login:login')
@require_GET
def input_book_info(request):
    book_main_class_list = BookClass.objects.filter(parent_id=0)
    if len(book_main_class_list) == 0:
        return render(request, 'input_book_info.html', {
            'book_main_class_list': [],
            'book_child_class_list': []
        })

    book_child_class_list = BookClass.objects.filter(parent_id=book_main_class_list[0].id)
    return render(request, 'input_book_info.html', {
        'book_main_class_list': list(book_main_class_list),
        'book_child_class_list': list(book_child_class_list)
    })


# 图书类型child
@require_GET
def update_child_class(request, main_class_id):
    book_child_class_list = BookClass.objects.values('id', 'name').filter(parent_id=main_class_id)
    return HttpResponse(json.dumps({
        'book_child_class_list': list(book_child_class_list)
    }))


# 登记图书信息
@login_required(login_url='login:login')
@require_POST
def commit_book_info(request):
    form = InputBookForms(request.POST)
    if not form.is_valid():
        data = {'code': error_code.INSERT_ERROR, 'msg': '登记图书失败'}
        return HttpResponse(json.dumps(data))
    if request.POST.get('id') == '':
        now_time = '%.0f' % (time.time() * 10 ** 7)
        picture_name = request.user.username + '-' + now_time + '.jpg'
        if 'cover_img' in request.FILES:
            cover_img = request.FILES['cover_img']
            upload_path = settings.COVER_IMG_PATH + os.path.sep + picture_name

            with open(upload_path, 'wb') as pic:
                for c in cover_img.chunks():
                    pic.write(c)
            upload_url = settings.STATIC_URL + 'cover_img/' + picture_name
        else:
            upload_url = settings.STATIC_URL + 'cover_img/default_cover.png'
        try:
            book = Book.objects.create(book_name=form.cleaned_data['book_name'],
                                       author=form.cleaned_data['author'],
                                       price=form.cleaned_data['price'],
                                       book_num=form.cleaned_data['book_num'],
                                       press=request.POST.get('press', ''),
                                       referee=request.POST.get('referee', ''),
                                       recommended_reasons=request.POST.get('recommended_reasons', ''),
                                       brief_introduction=request.POST.get('brief_introduction', ''),
                                       cover_img_pathname=upload_url)
            print('99999--' + request.POST.get('book_class'))
            add_book_class(request.POST.get('book_class', ''), book)
            book.save()
            data = {'code': error_code.SUCCESS, 'msg': '登记图书成功'}
            return HttpResponse(json.dumps(data))
        except Exception as e:
            print(e)
            data = {'code': error_code.INSERT_ERROR, 'msg': '登记图书失败'}
            return HttpResponse(json.dumps(data))
    else:
        now_time = '%.0f' % (time.time() * 10 ** 7)
        picture_name = request.user.username + '-' + now_time + '.jpg'
        upload_url = ''
        if 'cover_img' in request.FILES:
            cover_img = request.FILES['cover_img']
            upload_path = settings.COVER_IMG_PATH + os.path.sep + picture_name

            with open(upload_path, 'wb') as pic:
                for c in cover_img.chunks():
                    pic.write(c)
            upload_url = settings.STATIC_URL + 'cover_img/' + picture_name

        try:
            book = Book.objects.get(id=request.POST.get('id'))
            book.book_name = form.cleaned_data['book_name']
            book.author = form.cleaned_data['author']
            book.price = form.cleaned_data['price']
            book.book_num = form.cleaned_data['book_num']
            book.press = request.POST.get('press', '')
            book.referee = request.POST.get('referee', '')
            book.recommended_reasons = request.POST.get('recommended_reasons', '')
            book.brief_introduction = request.POST.get('brief_introduction', '')
            if upload_url == '':
                book.cover_img_pathname = book.cover_img_pathname
            else:
                book.cover_img_pathname = upload_url
            add_book_class(request.POST.get('book_class', ''), book)
            book.save()

            data = {'code': error_code.SUCCESS, 'msg': '修改图书成功'}
            return HttpResponse(json.dumps(data))
        except Exception:
            data = {'code': error_code.UPDATE_ERROR, 'msg': '修改图书失败'}
            return HttpResponse(json.dumps(data))


def add_book_class(book_class_ids, book):
    if book_class_ids != '':
        book_class_ids = book_class_ids.split(';')
        for book_class_id in book_class_ids:
            book_class_id = book_class_id.split('/')
            main_class_id = book_class_id[0]
            child_class_id = book_class_id[1]
            class_id = child_class_id if child_class_id != '-1' else main_class_id
            book_class = BookClass.objects.filter(id=class_id)
            if len(book_class) != 1:
                data = {'code': error_code.DATA_ABNORMAL, 'msg': '图书类别有误'}
                return HttpResponse(json.dumps(data))
            book.bookclass_set.add(book_class[0])


def form_book_class_str(book):
    book_class_list = []
    for book_class in book.bookclass_set.all():
        if book_class.parent_id == 0:
            book_class_list.append(book_class.name + '/无')
        else:
            main_class = BookClass.objects.filter(id=book_class.parent_id)
            if len(main_class) != 1:
                continue
            book_class_list.append(main_class[0].name + '/' + book_class.name)
    return book_class_list


# 图书详细信息
@login_required(login_url='login:login')
@require_GET
def book_detailed_info(request, book_id):
    book = Book.objects.get(id=book_id)
    book_class = form_book_class_str(book)

    return render(request, 'book_detail_info.html', {
        'book_detail_info': book,
        'book_class_list': book_class
    })


# 借阅图书
@login_required(login_url='login:login')
@csrf_exempt
@require_POST
def book_borrowing(request):

book_borrow/templates/home_footer.html
<footer class="footer">
  <div class="container">
    <span class="text-muted">© 山西方是科技有限公司</span>
  </div>
</footer>

book_borrow/templates/home_header.html
<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <span class="navbar-brand">方是图书借阅系统</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'book_borrow:index' %}">首页</a>
            </li>
            {% if 'profiles.borrow_book' in request.user.get_group_permissions %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:book_borrow_items' %}">借阅情况</a>
                </li>
            {% endif %}
            {% if 'profiles.see_book_borrow_history' in request.user.get_group_permissions %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:borrow_history' %}">历史借阅</a>
                </li>
            {% endif %}
            {% if 'profiles.write_book_info' in request.user.get_group_permissions %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:input_book_info' %}">登记图书</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:jump_class_tree' %}">图书类型</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:book_lists' %}">图书列表</a>
                </li>
            {% endif %}
            {% if 'profiles.edit_user' in request.user.get_group_permissions %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'book_borrow:user_manage' %}">用户管理</a>
                </li>
            {% endif %}

          </ul>
          {% if not request.user.is_authenticated %}
             <a class="btn btn-outline-light" href="{% url 'login:login' %}">登录</a>
            {% else %}
            <form name="logout" method="post" action="{% url 'login:logout' %}" class="form-inline mt-2 mt-md-0">
                {% csrf_token %}
                <span class="mr-sm-2" style="color: #ffffff">欢迎,{{ request.user.first_name }}</span>
                <a href="javascript:document.logout.submit()" class="btn btn-outline-light">注销</a>
            </form>
        {% endif %}
        </div>
      </nav>
</header>

book_borrow/templates/input_book_class.html
{% extends 'home_base.html' %}

{% load static %}

{% block head_link %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
    <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-treegrid/0.2.0/css/jquery.treegrid.min.css">
{% endblock %}
{% block javascript %}
    <script src="{% static 'js/bootstrap-table.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-table-treegrid.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-table-zh-CN.min.js' %}"></script>
    <script src="{% static 'js/jquery.treegrid.min.js' %}"></script>
{% endblock %}
{% block main %}
    <!-- Begin page content -->
    <main role="main" class="container">
        <div class="row mb-5"></div>
        <div class="row mb-2">
            <h2>图书类型</h2>
            <div>
                <button type="button" class="btn btn-info"
                    style="margin-left: 20px" onclick="add_main_class()">添加图书类型</button>
            </div>
        </div>
        <table id="table"></table>

        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="modal-body">

              </div>
              <div class="modal-footer" id="modal-footer">

              </div>
            </div>
          </div>
        </div>
    </main>
{% endblock %}

{% block javascript_code %}
    function add_main_class(){
        $('#modal-body').html('');
        $('#exampleModalLongTitle').html('');
        $('#modal-footer').html('');
        $('#exampleModalLongTitle').append('添加图书类型');
        $.ajax({
            type : "get",
            dataType : "json",
            data :{
                parent_id: 0
            },
            url: "{% url 'book_borrow:find_book_class_parent' %}",
            success : function(data) {
                var body_header = "<div class='mb-3'><label>选择上级类型</label><select class='form-control' id='main_class'>";
                var body_main = "";
                var body_footer = "</select></div>";
                body_main +="<option value='无'>无</option>"
                for (var i = 0; i < data.book_class.length; i++) {
                    body_main += "<option value='"+ data.book_class[i].id +"'>"+ data.book_class[i].name +"</option>"
                }

                var body = body_header+body_main+body_footer
                $('#modal-body').append(body);
                $('#modal-body').append("<div class='mb-3'><label for='book_main_class'>图书类型</label><input type='text' class='form-control' id='book_main_class' placeholder='请输入图书类型'></div>");
            },
            error : function(data){

            }
        });


        $('#modal-footer').append("<button type='button' class='btn btn-primary' onclick='submit_main_class()'>保存</button><button type='button' class='btn btn-secondary' data-dismiss='modal'>取消</button>");
        $('#exampleModalCenter').modal('show');
    }

    function submit_main_class(){
        var parent_id = $('#main_class').val();
        var book_class_name = $('#book_main_class').val();
        var book_class_data = {}

        if(book_class_name==""){
            $('#modal-body').append("<div class='mb-3'><div class='alert alert-danger' role='alert'>请填写图书类型</div></div>");
        }else{
            if(parent_id=="无"){
                book_class_data={
                    parent_id:0,
                    name:book_class_name
                }
            }else{
                book_class_data={
                    parent_id:parent_id,
                    name:book_class_name
                }
            }

            $.ajax({
                type : "POST",
                dataType : "json",
                data :book_class_data,
                url: "{% url 'book_borrow:input_book_class' %}",
                success : function(data) {
                    $('#modal-body').html('')
                    $('#exampleModalLongTitle').html('');
                    $('#modal-footer').html('')
                    $('#exampleModalLongTitle').append('添加图书类型');
                    $('#modal-body').append("<p>"+data.msg+"</p>")
                    $('#modal-footer').append("<button type='button' class='btn btn-secondary' onclick='location.reload()'>确定</button>")
                    $('#exampleModalCenter').modal('show')
                },
                error : function(data){
                    $('#modal-body').html('');
                    $('#exampleModalLongTitle').html('');
                    $('#modal-footer').html('')
                    $('#exampleModalLongTitle').append('添加图书类型');
                    $('#modal-body').append("<p>添加一级图书类型失败</p>");
                    $('#modal-footer').append("<button type='button' class='btn btn-secondary' data-dismiss='modal'>确定</button>")
                    $('#exampleModalCenter').modal('show');
                }
            });
        }
    }

    var $table = $('#table');
    $(function() {
        $table.bootstrapTable({
            url: '{% url 'book_borrow:book_class_tree' %}',
            striped: true,
            sidePagination: 'server',
            locale:'zh-CN',
            columns: [
                {
                    field: 'name',
                    title: '图书类型',
                },
                {
                    field: 'button',
                    title: '操作',
                    sortable: false,
                    align: 'center',
                    formatter:function(value, row , index){
                        return "<button type='button' class='btn btn-success btn-sm' style='margin-right: 10px' onclick=\"update_class_btn("+ row.id + ","+ row.parent_id +",'"+row.name+"')\">编辑</button><button type='button' class='btn btn-danger btn-sm' onclick='del_class_btn("+ row.id +")'>删除</button>";

                    }
                }
            ],
            treeShowField: 'name',
            parentIdField: 'parent_id',
            onLoadSuccess: function() {
                $table.treegrid({
                    treeColumn: 0,
                    onChange: function() {
                        $table.bootstrapTable('resetWidth');
                    }
                });
            }
        });
    });

    function update_class_btn(book_class_id,parent_id,book_class_name){
        $('#modal-body').html('');
        $('#exampleModalLongTitle').html('');
        $('#modal-footer').html('');
        $('#exampleModalLongTitle').append('修改图书类型');
        if(parent_id==0){
            $('#modal-body').append("<div class='mb-3'><label for='book_main_class'>图书类型</label><input type='text' class='form-control' id='book_main_class' value='"+book_class_name+"'></div>");
        }else{
            $.ajax({
                type : "get",
                dataType : "json",
                data :{
                    parent_id: 0
                },
                url: "{% url 'book_borrow:find_book_class_parent' %}",
                success : function(data) {
                    var body_header = "<div class='mb-3'><label>选择上级类型</label><select class='form-control' id='main_class'>";
                    var body_main = "";
                    var body_footer = "</select></div>";
                    for (var i = 0; i < data.book_class.length; i++) {
                        if(parent_id==data.book_class[i].id){
                            body_main += "<option value='"+ data.book_class[i].id +"' selected='selected'>"+ data.book_class[i].name +"</option>"
                        }else{
                            body_main += "<option value='"+ data.book_class[i].id +"'>"+ data.book_class[i].name +"</option>"
                        }

                    }

                    var body = body_header+body_main+body_footer
                    $('#modal-body').append(body);
                    $('#modal-body').append("<div class='mb-3'><label for='book_main_class'>图书类型</label><input type='text' class='form-control' id='book_main_class' value='"+book_class_name+"'></div>");
                },
                error : function(data){

                }
            });
        }
        $('#modal-footer').append("<button type='button' class='btn btn-success' onclick='update_book_class("+book_class_id+")'>修改</button><button type='button' class='btn btn-secondary' data-dismiss='modal'>取消</button>");
        $('#exampleModalCenter').modal('show');
    }


    function update_book_class(book_class_id){
        var parent_id = $('#main_class').val();
        var book_class_name = $('#book_main_class').val();
        var book_class_data = {}

        if(book_class_name==""){
            $('#modal-body').append("<div class='mb-3'><div class='alert alert-danger' role='alert'>请填写图书类型</div></div>");
        }else{
            if(parent_id=="无"){
                book_class_data={
                    book_class_id:book_class_id,
                    parent_id:0,
                    name:book_class_name
                }
            }else{
                book_class_data={
                    book_class_id:book_class_id,
                    parent_id:parent_id,
                    name:book_class_name
                }
            }

            $.ajax({
                type : "POST",
                dataType : "json",
                data :book_class_data,
                url: "{% url 'book_borrow:update_book_class' %}",
                success : function(data) {
                    $('#modal-body').html('')
                    $('#exampleModalLongTitle').html('');
                    $('#modal-footer').html('')
                    $('#exampleModalLongTitle').append('修改图书类型');
                    $('#modal-body').append("<p>"+data.msg+"</p>")
                    $('#modal-footer').append("<button type='button' class='btn btn-secondary' onclick='location.reload()'>确定</button>")
                    $('#exampleModalCenter').modal('show')
                },
                error : function(data){
                    $('#modal-body').html('');
                    $('#exampleModalLongTitle').html('');
                    $('#modal-footer').html('')
                    $('#exampleModalLongTitle').append('修改图书类型');
                    $('#modal-body').append("<p>修改图书类型失败</p>");
                    $('#modal-footer').append("<button type='button' class='btn btn-secondary' data-dismiss='modal'>确定</button>")
                    $('#exampleModalCenter').modal('show');
                }
            });
        }
    }



    function del_class_btn(book_class_id){
        $('#modal-body').html('');
        $('#exampleModalLongTitle').html('');
        $('#modal-footer').html('')
        $('#exampleModalLongTitle').append('删除图书类型');
        $('#modal-body').append("<p>确认删除该图书类型吗?</p>");
        $('#modal-footer').append("<button type='button' class='btn btn-danger' onclick='del_book_class("+book_class_id+")'>删除</button><button type='button' class='btn btn-secondary' data-dismiss='modal'>取消</button>")
        $('#exampleModalCenter').modal('show');
    }

    function del_book_class(book_class_id){
        $.ajax({
            type : "POST",
            dataType : "json",
            data :{
                book_class_id: book_class_id
            },
            url: "{% url 'book_borrow:del_book_class' %}",
            success : function(data) {
                $('#modal-body').html('')
                $('#exampleModalLongTitle').html('');
                $('#modal-footer').html('')
                $('#exampleModalLongTitle').append('删除图书类型');
                $('#modal-body').append("<p>"+data.msg+"</p>")
                $('#modal-footer').append("<button type='button' class='btn btn-secondary' onclick='location.reload()'>确定</button>")
                $('#exampleModalCenter').modal('show')
            },
            error : function(data){
                $('#modal-body').html('');
                $('#exampleModalLongTitle').html('');
                $('#modal-footer').html('')
                $('#exampleModalLongTitle').append('删除图书类型');
                $('#modal-body').append("<p>删除图书类型失败</p>");
                $('#modal-footer').append("<button type='button' class='btn btn-secondary' data-dismiss='modal'>确定</button>")
                $('#exampleModalCenter').modal('show');
            }
        });

    }
{% endblock %}